### ISSUE TITLE
Move to Vue.js  ?

### ISSUE THREAD

**Issue by altuntasfatih** [Unichain-turkey/unichainturkey.com#1]
Gençler siteyi vue.js taşıyalım diyorum ne dersin ?
Vue.js component olarak oluştururuz ,demo uygulamayalar daha rahat bir şekilde sitemize koyarız

**Comment by mevlanaayas** [comment]
Long Live  Foter +1

> genişletilebilir ve okunaklı bir proje ortaya çıkar kanaatindeyim

**Comment by onursabitsalman** [comment]
Run Foter Run.

-Close issue pls

**Comment by altuntasfatih** [comment]
https://github.com/Unichain-turkey/unichaintr-vue.com
